services:
  challenge:
    build:
      context: .
    restart: always
    ports:
      - 5000:5000
    environment:
      - FLAG=winterhack{adm1n_4cc3ss_gr4nt3d}
      - ADMIN_PASSWORD=FAKE_PASSWORD